# Generated by Django 5.2.2 on 2025-06-07 19:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_document_options_remove_document_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Document',
            new_name='UploadedDocument',
        ),
        migrations.RenameIndex(
            model_name='uploadeddocument',
            new_name='documents_u_uploade_fde306_idx',
            old_name='documents_d_uploade_28af31_idx',
        ),
    ]
