# Generated by Django 5.2.2 on 2025-06-07 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_rename_document_uploadeddocument_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadeddocument',
            name='page_count',
            field=models.IntegerField(default=0, help_text='Number of pages in the document'),
        ),
    ]
